version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - GOOGLE_CLOUD_PROJECT_ID=160372229474
      - GOOGLE_CLOUD_REGION=us-central1
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./backend/src:/app/src
    networks:
      - ipaas-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - ipaas-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  ipaas-network:
    driver: bridge

volumes:
  node_modules_backend:
  node_modules_frontend:
